### ISSUE TITLE
Running d4m-nfs.sh gives something wrong with /etc/exports file error.

### ISSUE THREAD

**Issue by TheDagger** [IFSight/d4m-nfs#38]
The error I get is **something is wrong with your /etc/exports file**

Here is attached image of the error I get.

![screen shot 2017-03-08 at 8 21 59 am](https://cloud.githubusercontent.com/assets/8128863/23712641/5f49be88-03d8-11e7-9742-203f614ddacb.png)

1. screenshot of Docker for Mac's Preferences -> File Sharing

![screen shot 2017-03-08 at 8 21 00 am](https://cloud.githubusercontent.com/assets/8128863/23712583/35094e54-03d8-11e7-896f-26aa92bc17a3.png)

2. attachment of d4m-nfs/etc/d4m-nfs-mounts.txt

/Users/josephastrahan:mnt:0:0

3. attachment of /tmp/d4m-mount-nfs.sh ?? (I don't think I need this right? I'm using docker-compose.yml files)

4. attachment of /tmp/d4m-nfs-mounts.txt

![screen shot 2017-03-08 at 8 56 45 am](https://cloud.githubusercontent.com/assets/8128863/23714197/33556b2e-03dd-11e7-9ad2-f85e4a16743f.png)

5. attachment of /etc/exports

-e # d4m-nfs exports

"/Users/josephastrahan" -alldirs -mapall=501:20 localhost

**Comment by TheDagger** [comment]
My ultimate goal is to get my docker-compose file to work where I can just docker-compose up -d and it works as usual.

Here is my docker compose file

```
version: "2"
services:
    dblive:
        image: mysql:5.5.52
        volumes:
            - ./db_data_live:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: distribution_live
            MYSQL_USER: adminlive
            MYSQL_PASSWORD: 1234
    dbdev:
        image: mysql:5.5.52
        volumes:
            - ./db_data_dev:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: distribution_dev
            MYSQL_USER: admindev
            MYSQL_PASSWORD: 1234
    
    phpmyadmin:
        depends_on:
            - dblive
            - dbdev
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_ARBITRARY : 1
        restart: always
        ports:
            - "8081:80"
            
    web:
        build: ./
        depends_on:
            - dblive
            - dbdev
        volumes:
            - ./web:/var/www
            - ./config/custom.php.ini:/etc/php5/apache2/conf.d/custom.php.ini
            - ./logs/apache_error.log:/var/log/apache2/error.log
            - ./logs/apache_access.log:/var/log/apache2/access.log
            - ./config/apache_default.conf:/etc/apache2/sites-available/000-default.conf
            - ./config/apache_default-ssl.conf:/etc/apache2/sites-available/default-ssl.conf
            - ./config/ssl/apache.key:/etc/apache2/ssl/apache.key
            - ./config/ssl/apache.crt:/etc/apache2/ssl/apache.crt
            - ./web/public_html/livesite:/app
            - ./web/public_html/devsite:/appdev
        restart: always
        ports: 
            #Standard HTTP Port
            - "80:80"
            #Below allows access to local computer from outside ports
            - "8080:80"
            #SSH Port
            - "443:443"
            #Below allows access to local computer from outside ports
            - "4443:443"
```
