### ISSUE TITLE
Error with mounting volumes with docker-compose

### ISSUE THREAD

**Issue by NikitaKharkov** [IFSight/d4m-nfs#41]
## The error is:

```
ERROR: for app-quota-api  Cannot start service app-quota-api: Mounts denied: es for more info.
.
rs/admin/la_projects/der-ibe/ibe-quotas-api
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespace
```

![image](https://cloud.githubusercontent.com/assets/19974632/24467698/3af8a9da-14be-11e7-94a1-3bedefc8e0ef.png)

`d4m-nfs/etc/d4m-nfs-mounts.txt`
```
/Users:/Users:0:0
/Volumes:/Volumes
/private:/private
```

`/etc/d4m-nfs-mounts.txt`
```
/Users:/Users:0:0
/Volumes:/Volumes
/private:/private
```

`/tmp/d4m-mount-nfs.sh`
```
ln -nsf /tmp/d4m-apk-cache /etc/apk/cache
apk update
apk add nfs-utils sntpc
rpcbind -s > /dev/null 2>&1

DEFGW=$(ip route|awk '/default/{print $3}')
FSTAB="\n\n# d4m-nfs mounts\n"

if true && ! $(grep ':/mnt' /tmp/d4m-nfs-mounts.txt > /dev/null 2>&1); then
  mkdir -p /mnt

  FSTAB="${FSTAB}${DEFGW}:/Users/admin /mnt nfs nolock,local_lock=all 0 0"
fi

if [ -e /tmp/d4m-nfs-mounts.txt ]; then
  while read MOUNT; do
    DSTDIR=$(echo "$MOUNT" | cut -d: -f2)
    mkdir -p ${DSTDIR}
    FSTAB="${FSTAB}\n${DEFGW}:$(echo "$MOUNT" | cut -d: -f1) ${DSTDIR} nfs nolock,local_lock=all 0 0"
  done < /tmp/d4m-nfs-mounts.txt
fi

if ! $(grep "d4m-nfs mounts" /etc/fstab > /dev/null 2>&1); then
    echo adding d4m nfs config to /etc/fstab:
    echo -e $FSTAB | tee /etc/fstab
else
    echo d4m nfs mounts already exist in /etc/fstab
fi

sntpc -i 10 ${DEFGW} &

sleep .5
mount -a
touch /tmp/d4m-done
```

`/tmp/d4m-nfs-mounts.txt`
```
/Users:/Users:0:0
/Volumes:/Volumes
/private:/private
```

` /etc/exports`
```
# d4m-nfs exports
"/Users" -alldirs -mapall=0:0 localhost
"/Volumes" -alldirs -mapall=0:0 localhost
"/private" -alldirs -mapall=0:0 localhost
```
## -------------------------------------------------------------------------
Looks like the problem is incorrect using strings... I am very weak in this, so I couldn't even assume where the problem is. 
https://github.com/IFSight/d4m-nfs/issues/32#issuecomment-284417804 - this similar problem in open issue, but the man don't say anything more about it... It's a pity.

I use docker-compose version 3. Maybe in this problem. When I used version 2 with `volume_from` everything was ok. But then I switched and try to write next lines:

```
php:
        build: docker/php
        restart: always
        container_name: mc_php
        links:
            - db
        volumes:
            - ./user-api:/var/www/microservice/user-api
            - ./quota-api:/var/www/microservice/quota-api
            - ./gateway-api:/var/www/microservice/gateway-api
```
